### ISSUE TITLE
Docker config doesn’t allow installing WordPress plugins

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmyblock-wordpress#12]
It’d be nice to be able to run `wp-cli` commands in the Docker container. (Maybe this is already possible?). Eg:

    wp plugin install --activate helpful
    wp plugin install --activate tag-list-widget

But, realistically, we should allow WordPress to install its own plugins, via the web interface, as this is what most newcomers will expect to do. 

Right now, it fails, instead asking for FTP connection details.

**Comment by sagepe** [comment]
Permissions changes as per #13 permit this to work. I have tested by installing (but not configuring) the plugins mentioned in #14 and #15.
