### ISSUE TITLE
Investigate how we could add a survey to the site on a banner if we needed to

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmyblock-wordpress#24]
At some point we need to do a survey of users - currently this will need to be online -to get some general feedback about the site and project for our M&E - we need to do this at least twice post "launch" to get an idea of change, ideally the first time should be close to the "launch" and the second should be close to the end of the project (Late october)

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/fixmyblock-wordpress/pull/35 – it’s a biggie, so going to review it myself later, then get it merged if it all still looks ok with fresh eyes ;-)
