### ISSUE TITLE
Add “Disrepair” to the glossary – and maybe write an article about what it means?

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmyblock-wordpress#40]
Rhiannon from SGTO noticed that, when she searched for “disrepair” only one page (the tenant action case study) turned up in the results.

She wasn’t sure whether this would really be an issue – after all, “disrepair” is a pretty technical term (and a legal term), and we’re more expecting that people will search for common words like "cracks" or "mould" or "damp".

_But_ @MyfanwyNixon, I did wonder whether we should _at least_ add “Disrepair” to the Glossary page?

If a description of disrepair is too much to fit into a paragraph in the Glossary, then maybe a new page on “What exactly is ‘Disrepair’?” might be useful?

**Comment by MyfanwyNixon** [comment]
Thanks Zarino, have added this to my Trello and will look at it this sprint or next.

**Comment by zarino** [comment]
@MyfanwyNixon’s done this one!
