### ISSUE TITLE
Symlink failed on first vagrant up

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/fixmyblock-wordpress#61]
```
# Symlink the theme into wordpress instance
symlink /home/vagrant/shared/fixmyblock-theme /home/vagrant/wordpress/wp-content/themes/fixmyblock-theme

```

Got a fail

```
default: ln: 
    default: failed to create symbolic link '/home/vagrant/wordpress/wp-content/themes/fixmyblock-theme': Permission denied
```

Which makes me think maybe it should be 

```
# Symlink the theme into wordpress instance
sudo_symlink /home/vagrant/shared/fixmyblock-theme /home/vagrant/wordpress/wp-content/themes/fixmyblock-theme

```

But maybe there's a reason it wasn't that already that I don't understand?

**Comment by zarino** [comment]
Ah, this’ll be because we recently changed the permissions on the `/home/vagrant/wordpress` directory, so that the web process has permission to write files there (for image uploads, wordpress updates, etc).

Yes, `sudo_symlink` would do the job now instead 👍

**Comment by zarino** [comment]
Well spotted!
